apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: esp32-iot-server-service
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.org/redirect-to-https: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
        - esp32-iot-server.brennonloveless.com
      secretName: esp32-iot-server-crt
  rules:
    - host: esp32-iot-server.brennonloveless.com
      http:
        paths:
          - path: /
            backend:
              serviceName: esp32-iot-server-service
              servicePort: 3000

